"""add referrer, user agent, and geolocation fields to clicks

Revision ID: 0ede9771497f
Revises: 78e4a6c3c84b
Create Date: 2026-07-26 17:26:42.721252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ede9771497f'
down_revision = '78e4a6c3c84b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clicks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referrer', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('browser', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('os', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('device_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('country_code', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_clicks_browser'), ['browser'], unique=False)
        batch_op.create_index(batch_op.f('ix_clicks_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_clicks_device_type'), ['device_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_clicks_os'), ['os'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clicks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clicks_os'))
        batch_op.drop_index(batch_op.f('ix_clicks_device_type'))
        batch_op.drop_index(batch_op.f('ix_clicks_country_code'))
        batch_op.drop_index(batch_op.f('ix_clicks_browser'))
        batch_op.drop_column('city')
        batch_op.drop_column('country_code')
        batch_op.drop_column('country')
        batch_op.drop_column('device_type')
        batch_op.drop_column('os')
        batch_op.drop_column('browser')
        batch_op.drop_column('user_agent')
        batch_op.drop_column('referrer')

    # ### end Alembic commands ###
