"""add expires_at to shortened_urls

Revision ID: 78e4a6c3c84b
Revises: f1642a260455
Create Date: 2026-07-18 15:46:02.952686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78e4a6c3c84b'
down_revision = 'f1642a260455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shortened_urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shortened_urls', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
