"""initial schema: shortened_urls and clicks

Revision ID: f1642a260455
Revises: 
Create Date: 2026-06-13 16:55:41.550770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1642a260455'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortened_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('alias', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shortened_urls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shortened_urls_alias'), ['alias'], unique=True)

    op.create_table('clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shortened_url_id', sa.Integer(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['shortened_url_id'], ['shortened_urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clicks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clicks_clicked_at'), ['clicked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_clicks_shortened_url_id'), ['shortened_url_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clicks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clicks_shortened_url_id'))
        batch_op.drop_index(batch_op.f('ix_clicks_clicked_at'))

    op.drop_table('clicks')
    with op.batch_alter_table('shortened_urls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shortened_urls_alias'))

    op.drop_table('shortened_urls')
    # ### end Alembic commands ###
